# Generated by Django 4.1 on 2022-08-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_auto_20220826_0009"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="_type",
            new_name="a_type",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="stauts",
            new_name="status",
        ),
    ]
